---
debname: helm
debver: 3.14.4-1
src_path: files
dl_files:
  helm-v3.14.4-linux-amd64.tar.gz:
    topdir: linux-amd64
    url: https://get.helm.sh/helm-v3.14.4-linux-amd64.tar.gz
    sha256sum: a5844ef2c38ef6ddf3b5a8f7d91e7e0e8ebc39a38bb3fc8013d629c1ef29c259
  helm-mapkubeapis_0.4.1_linux_amd64.tar.gz:
    topdir: mapkubeapis
    url: https://github.com/helm/helm-mapkubeapis/releases/download/v0.4.1/helm-mapkubeapis_0.4.1_linux_amd64.tar.gz
    sha256sum: e90a22c4acee76774589042f6a5901e136ee33c10630790d6cff37d169905a78

revision:
  dist: $STX_DIST
  GITREVCOUNT:
    BASE_SRCREV: f98b1a5b40c01f54e407d1aaa1a5945c6beeb6c5
