---
debname: k8s-pod-recovery
debver: 1.0-1
src_path: centos/files
revision:
  dist: $STX_DIST
  PKG_GITREVCOUNT: true
  SRC_GITREVCOUNT:
    SRC_BASE_SRCREV: 3d5e02157851d140f7cddacbe5086f6e6c12e26c
