---
debname: runc
debver: 1.1.7
src_path: null
dl_files:
  runc.arm64:
    topdir: null
    url: https://github.com/opencontainers/runc/releases/download/v1.1.7/runc.arm64
    sha256sum: 1b309c4d5aa4cc7b888b2f79c385ecee26ca3d55dae0852e7c4a692196d5faab
revision:
  dist: $STX_DIST
  GITREVCOUNT:
    BASE_SRCREV: fe5768d72e8ad2f1d780cfaab11294998d5ed377
    SRC_DIR: ${MY_REPO}/stx/integ/kubernetes/runc
