---
debname: runc
debver: 1.0.2+ds1-2
dl_path:
  name: runc-debian-1.0.2+ds1-2.tar.gz
  url: https://salsa.debian.org/go-team/packages/runc/-/archive/debian/1.0.2+ds1-2/runc-debian-1.0.2+ds1-2.tar.gz
  md5sum: b5d8a40e5def530abb66f6555c0f55a7
  sha256sum: 7d4d68f2e9f15881fd55de723ee507fbefc396a184ebbeda0cbc560983fd1689
revision:
  dist: $STX_DIST
  GITREVCOUNT:
    BASE_SRCREV: fe5768d72e8ad2f1d780cfaab11294998d5ed377
    SRC_DIR: ${MY_REPO}/stx/integ/kubernetes/runc
